# Generated by Django 3.0.7 on 2020-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200613_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
