# Generated by Django 3.0.6 on 2020-05-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('learn_list1', models.CharField(max_length=250)),
                ('learn_list2', models.CharField(max_length=250)),
                ('learn_list3', models.CharField(max_length=250)),
                ('completion_list1', models.CharField(max_length=250)),
                ('completion_list2', models.CharField(blank=True, max_length=250)),
                ('weekday_datetime', models.DateTimeField()),
                ('weekends_datetime', models.DateTimeField()),
                ('photo_course', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_next_event', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Category')),
            ],
        ),
    ]
