# Generated by Django 3.0.6 on 2020-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200601_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo_course',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/'),
        ),
    ]
