# Generated by Django 3.0.7 on 2020-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200603_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='completion_list1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_list1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_list2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='weekday_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='weekends_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
