# Generated by Django 3.0.7 on 2020-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200617_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='weekday_datetime',
        ),
        migrations.AlterField(
            model_name='course',
            name='weekends_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
