# Generated by Django 3.0.7 on 2020-06-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200618_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='weekends_datetime',
            new_name='datetime',
        ),
    ]
