# Generated by Django 3.0.7 on 2020-06-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('courses', '0010_auto_20200618_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.Team'),
        ),
    ]
